"use strict";
// should correspond to test/.serverless/configuration-template-update.json

exports.apiGroup = {
  "GroupName": "my_service_dev_api",
  "Description": "API group for Function Compute service my-service-dev, generated by the Serverless framework.",
  "Region": "cn-shanghai"
};

exports.apis = [{
  "GroupName": "my_service_dev_api",
  "ApiName": "sls_http_my_service_dev_currentTime",
  "Visibility": "PUBLIC",
  "Description": "API for Function Compute function my-service-dev-currentTime of service my-service-dev, triggered by http event, generated by the Serverless framework.",
  "AuthType": "ANONYMOUS",
  "RequestConfig": {
    "RequestProtocol": "HTTP",
    "RequestHttpMethod": "POST",
    "RequestPath": "/ping",
    "BodyFormat": "FORM",
    "PostBodyDescription": ""
  },
  "ServiceConfig": {
    "ServiceProtocol": "FunctionCompute",
    "Mock": "FALSE",
    "ServiceTimeout": 3000,
    "FunctionComputeConfig": {
      "FcRegionId": "cn-shanghai",
      "ServiceName": "my-service-dev",
      "FunctionName": "my-service-dev-currentTime"
    },
    "ContentTypeValue": "application/json; charset=UTF-8"
  },
  "RequestParameters": [
    {
      "ApiParameterName": "foo",
      "ParameterType": "String",
      "Location": "Body",
      "Required": "OPTIONAL",
      "isHide": false,
      "DefaultValue": "bar",
      "DemoValue": "bar",
      "Description": "foo"
    }
  ],
  "ServiceParameters": [
    {
      "ServiceParameterName": "foo",
      "Type": "String",
      "Location": "Body",
      "ParameterCatalog": "REQUEST"
    }
  ],
  "ServiceParametersMap": [
    {
      "ServiceParameterName": "foo",
      "RequestParameterName": "foo"
    }
  ],
  "ResultType": "JSON",
  "ResultSample": "{}"
}, {
  "GroupName": "my_service_dev_api",
  "ApiName": "sls_http_my_service_dev_currentTime2",
  "Visibility": "PUBLIC",
  "Description": "API for Function Compute function my-service-dev-currentTime2 of service my-service-dev, triggered by http event, generated by the Serverless framework.",
  "AuthType": "ANONYMOUS",
  "RequestConfig": {
    "RequestProtocol": "HTTP",
    "RequestHttpMethod": "GET",
    "RequestPath": "/ping2",
    "BodyFormat": "",
    "PostBodyDescription": ""
  },
  "ServiceConfig": {
    "ServiceProtocol": "FunctionCompute",
    "Mock": "FALSE",
    "ServiceTimeout": 3000,
    "FunctionComputeConfig": {
      "FcRegionId": "cn-shanghai",
      "ServiceName": "my-service-dev",
      "FunctionName": "my-service-dev-currentTime2"
    },
    "ContentTypeValue": "application/json; charset=UTF-8"
  },
  "RequestParameters": [],
  "ServiceParameters": [],
  "ServiceParametersMap": [],
  "ResultType": "JSON",
  "ResultSample": "{}"
}];

exports.group = {
  "GroupName": "my_service_dev_api",
  "Description": "API group for Function Compute service my-service-dev, generated by the Serverless framework.",
  "Region": "cn-shanghai"
};

exports.fullGroup = {
  "GroupName": "my_service_dev_api",
  "Description": "API group for Function Compute service my-service-dev, generated by the Serverless framework.",
  "GroupId": "523e8dc7bbe04613b5b1d726c2a7889d",
  "SubDomain": "523e8dc7bbe04613b5b1d726c2a7889d-cn-shanghai.alicloudapi.com"
};

exports.role = {
  "RoleName": "SLSFCInvocationFromAPIGateway",
  "Description": "Allow Function Compute Service to be visited by API Gateway, generated by the Serverless framework",
  "AssumeRolePolicyDocument": {
    "Version": "1",
    "Statement": [
      {
        "Action": "sts:AssumeRole",
        "Effect": "Allow",
        "Principal": {
          "Service": [
            "apigateway.aliyuncs.com"
          ]
        }
      }
    ]
  },
  "Policies": [
    {
      "PolicyType": "System",
      "PolicyName": "AliyunFCInvocationAccess",
      "RoleName": "SLSFCInvocationFromAPIGateway"
    }
  ]
};

exports.fullRole =  {
  "RoleId": "901234567890123",
  "RoleName": "SLSFCInvocationFromAPIGateway",
  "Arn": "acs:ram::1234567890123456:role/SLSFCInvocationFromAPIGateway"
}

exports.fullApis = [{
  "ApiName": "sls_http_my_service_dev_currentTime",
  "ApiId": '4134134134141'
}, {
  "ApiName": "sls_http_my_service_dev_currentTime2",
  "ApiId": '413243280141'
}];


exports.functions = [{
  "name": "my-service-dev-currentTime",
  "service": "my-service-dev",
  "handler": "index.ping",
  "memorySize": 128,
  "timeout": 30,
  "runtime": "nodejs4.4",
  "code": {
    "ossBucketName": "sls-my-service",
    "ossObjectName": "serverless/my-service/dev/1500622721413-2017-07-21T07:38:41.413Z/my-service.zip"
  }
  }, {
  "name": "my-service-dev-currentTime2",
  "service": "my-service-dev",
  "handler": "index.ping",
  "memorySize": 128,
  "timeout": 30,
  "runtime": "nodejs4.4",
  "code": {
    "ossBucketName": "sls-my-service",
    "ossObjectName": "serverless/my-service/dev/1500622721413-2017-07-21T07:38:41.413Z/my-service.zip"
  }
}];