'use strict';

const fs = require('fs');
const path = require('path');

const sinon = require('sinon');
const BbPromise = require('bluebird');

const AliyunProvider = require('../../provider/aliyunProvider');
const AliyunDeploy = require('../aliyunDeploy');
const Serverless = require('../../test/serverless');

describe('setupTriggers', () => {
  let serverless;
  let aliyunDeploy;

  const apiGroup = {
    "GroupName": "my-service-dev-api",
    "Description": "API group for Function Compute service my-service-dev, generated by the Serverless framework.",
    "Region": "cn-hangzhou"
  };

  const apis = [{
    "GroupName": "my-service-dev-api",
    "ApiName": "sls-http-my-service-dev-currentTime",
    "Visibility": "PUBLIC",
    "Description": "API for Function Compute function my-service-dev-currentTime of service my-service-dev, triggered by http event, generated by the Serverless framework.",
    "AuthType": "ANONYMOUS",
    "RequestConfig": {
      "RequestProtocol": "HTTP",
      "RequestHttpMethod": "GET",
      "RequestPath": "/ping",
      "RequestParameters": [],
      "BodyFormat": "",
      "PostBodyDescription": ""
    },
    "ServiceConfig": {
      "ServiceProtocol": "FunctionCompute",
      "Mock": "FALSE",
      "ServiceTimeout": 3000,
      "FunctionComputeConfig": {
        "FcRegionId": "cn-hangzhou",
        "ServiceName": "my-service-dev",
        "FunctionName": "my-service-dev-currentTime"
      },
      "ContentTypeValue": "application/json; charset=UTF-8"
    },
    "ResultType": "JSON",
    "ResultSample": "{}"
  }, {
    "GroupName": "my-service-dev-api",
    "ApiName": "sls-http-my-service-dev-currentTime2",
    "Visibility": "PUBLIC",
    "Description": "API for Function Compute function my-service-dev-currentTime2 of service my-service-dev, triggered by http event, generated by the Serverless framework.",
    "AuthType": "ANONYMOUS",
    "RequestConfig": {
      "RequestProtocol": "HTTP",
      "RequestHttpMethod": "GET",
      "RequestPath": "/ping2",
      "RequestParameters": [],
      "BodyFormat": "",
      "PostBodyDescription": ""
    },
    "ServiceConfig": {
      "ServiceProtocol": "FunctionCompute",
      "Mock": "FALSE",
      "ServiceTimeout": 3000,
      "FunctionComputeConfig": {
        "FcRegionId": "cn-hangzhou",
        "ServiceName": "my-service-dev",
        "FunctionName": "my-service-dev-currentTime2"
      },
      "ContentTypeValue": "application/json; charset=UTF-8"
    },
    "ResultType": "JSON",
    "ResultSample": "{}"
  }];

  const group = {
    "GroupName": "my-service-dev-api",
    "Description": "API group for Function Compute service my-service-dev, generated by the Serverless framework.",
    "Region": "cn-hangzhou"
  };

  const fullGroup = {
    "GroupName": "my-service-dev-api",
    "Description": "API group for Function Compute service my-service-dev, generated by the Serverless framework.",
    "GroupId": "523e8dc7bbe04613b5b1d726c2a7889d",
    "SubDomain": "523e8dc7bbe04613b5b1d726c2a7889d-cn-hangzhou.alicloudapi.com"
  };

  const role = {
    "RoleName": "SLSFCInvocationFromAPIGateway",
    "Description": "Allow Function Compute Service to be visited by API Gateway, generated by the Serverless framework",
    "AssumeRolePolicyDocument": {
      "Version": "1",
      "Statement": [
        {
          "Action": "sts:AssumeRole",
          "Effect": "Allow",
          "Principal": {
            "Service": [
              "apigateway.aliyuncs.com"
            ]
          }
        }
      ]
    },
    "Policies": [
      {
        "PolicyType": "System",
        "PolicyName": "AliyunFCInvocationAccess",
        "RoleName": "SLSFCInvocationFromAPIGateway"
      }
    ]
  };

  const fullRole =  {
    "RoleId": "901234567890123",
    "RoleName": "SLSFCInvocationFromAPIGateway",
    "Arn": "acs:ram::1234567890123456:role/SLSFCInvocationFromAPIGateway"
  }

  const fullApis = [{
    "ApiName": "sls-http-my-service-dev-currentTime",
    "ApiId": '4134134134141'
  }, {
    "ApiName": "sls-http-my-service-dev-currentTime2",
    "ApiId": '413243280141'
  }];

  beforeEach(() => {
    serverless = new Serverless();
    serverless.service.service = 'my-service';
    serverless.service.provider = {
      name: 'aliyun',
      credentials: path.join(__dirname, '..', '..', 'test', 'credentials'),
    };
    serverless.config = {
      servicePath: path.join(__dirname, '..', '..', 'test')
    };
    const options = {
      stage: 'dev',
      region: 'cn-hangzhou',
    };
    serverless.setProvider('aliyun', new AliyunProvider(serverless, options));
    aliyunDeploy = new AliyunDeploy(serverless, options);
  });

  describe('#setupTriggers()', () => {
    let createApisIfNeededStub;
    let createTriggersIfNeededStub;

    beforeEach(() => {
      createApisIfNeededStub = sinon.stub(aliyunDeploy, 'createApisIfNeeded')
        .returns(BbPromise.resolve());
      createTriggersIfNeededStub = sinon.stub(aliyunDeploy, 'createTriggersIfNeeded')
        .returns(BbPromise.resolve());
    });

    afterEach(() => {
      aliyunDeploy.createApisIfNeeded.restore();
      aliyunDeploy.createTriggersIfNeeded.restore();
    });

    it('should run promise chain', () => aliyunDeploy
      .setupTriggers().then(() => {
        expect(createApisIfNeededStub.calledOnce).toEqual(true);
        expect(createTriggersIfNeededStub.calledAfter(createApisIfNeededStub));
      })
    );

    it('should set apis property', () => {
      return aliyunDeploy.setupTriggers().then(() => {
          expect(aliyunDeploy.apis).toEqual(apis);
        });
      }
    );
  });


  describe('#setupTriggers()', () => {
    let getApiGroupStub;
    let createApiGroupStub;
    let getApiRoleStub;
    let createApiRoleStub;
    let getPoliciesStub;
    let createPolicyStub;
    let getApisStub;
    let updateApiStub;
    let createApiStub;
    let deployApiStub;
    let consoleLogStub;

    beforeEach(() => {
      getApiGroupStub = sinon.stub(aliyunDeploy.provider, 'getApiGroup');
      createApiGroupStub = sinon.stub(aliyunDeploy.provider, 'createApiGroup');
      getApiRoleStub = sinon.stub(aliyunDeploy.provider, 'getApiRole');
      createApiRoleStub = sinon.stub(aliyunDeploy.provider, 'createApiRole');
      getPoliciesStub = sinon.stub(aliyunDeploy.provider, 'getPolicies');
      createPolicyStub = sinon.stub(aliyunDeploy.provider, 'createPolicy');
      getApisStub = sinon.stub(aliyunDeploy.provider, 'getApis');
      updateApiStub = sinon.stub(aliyunDeploy.provider, 'updateApi');
      createApiStub = sinon.stub(aliyunDeploy.provider, 'createApi');
      deployApiStub = sinon.stub(aliyunDeploy.provider, 'deployApi');
      consoleLogStub = sinon.stub(aliyunDeploy.serverless.cli, 'log').returns();
    });

    afterEach(() => {      
      aliyunDeploy.provider.getApiGroup.restore();
      aliyunDeploy.provider.createApiGroup.restore();
      aliyunDeploy.provider.getApiRole.restore();
      aliyunDeploy.provider.createApiRole.restore();
      aliyunDeploy.provider.getPolicies.restore();
      aliyunDeploy.provider.createPolicy.restore();
      aliyunDeploy.provider.getApis.restore();
      aliyunDeploy.provider.updateApi.restore();
      aliyunDeploy.provider.createApi.restore();
      aliyunDeploy.provider.deployApi.restore();
      aliyunDeploy.serverless.cli.log.restore();
    });

    it('should set up apis property from scratch', () => {
      getApiGroupStub.returns(BbPromise.resolve(undefined));
      createApiGroupStub.returns(BbPromise.resolve(fullGroup));
      getApiRoleStub.returns(BbPromise.resolve(undefined));
      createApiRoleStub.returns(BbPromise.resolve(fullRole));
      getPoliciesStub.returns(BbPromise.resolve([]));
      createPolicyStub.returns(BbPromise.resolve(role.Policies[0]));
      getApisStub.returns(BbPromise.resolve([]));
      updateApiStub.returns(BbPromise.resolve());
      createApiStub.onCall(0).returns(BbPromise.resolve(fullApis[0]));
      createApiStub.onCall(1).returns(BbPromise.resolve(fullApis[1]));
      deployApiStub.returns(BbPromise.resolve());

      return aliyunDeploy.setupTriggers().then(() => {
        expect(getApiGroupStub.calledOnce).toEqual(true);
        expect(getApiGroupStub.calledWithExactly('my-service-dev-api')).toEqual(true);

        expect(createApiGroupStub.calledAfter(getApiGroupStub)).toEqual(true);
        expect(createApiGroupStub.calledOnce).toEqual(true);
        expect(createApiGroupStub.calledWithExactly(apiGroup)).toEqual(true);

        expect(getApiRoleStub.calledAfter(createApiGroupStub)).toEqual(true);
        expect(getApiRoleStub.calledOnce).toEqual(true);
        expect(getApiRoleStub.calledWithExactly('SLSFCInvocationFromAPIGateway')).toEqual(true);

        expect(createApiRoleStub.calledAfter(getApiRoleStub)).toEqual(true);
        expect(createApiRoleStub.calledOnce).toEqual(true);
        expect(createApiRoleStub.calledWithExactly(role)).toEqual(true);

        expect(getPoliciesStub.calledAfter(createApiRoleStub)).toEqual(true);
        expect(getPoliciesStub.calledOnce).toEqual(true);
        expect(getPoliciesStub.calledWithExactly(role)).toEqual(true);

        expect(createPolicyStub.calledAfter(getPoliciesStub)).toEqual(true);
        expect(createPolicyStub.calledOnce).toEqual(true);
        expect(createPolicyStub.calledWithExactly(role.Policies[0])).toEqual(true);

        expect(getApisStub.calledAfter(createPolicyStub)).toEqual(true);
        expect(getApisStub.calledOnce).toEqual(true);
        expect(getApisStub.calledWithExactly({
          GroupId: fullGroup.GroupId
        })).toEqual(true);

        expect(updateApiStub.called).toEqual(false);

        expect(createApiStub.calledAfter(getApisStub)).toEqual(true);
        expect(createApiStub.calledTwice).toEqual(true);

        expect(createApiStub.calledWithExactly(
          fullGroup,
          fullRole,
          apis[0]
        )).toEqual(true);
        expect(createApiStub.calledWithExactly(
          fullGroup,
          fullRole,
          apis[1]
        )).toEqual(true);

        expect(deployApiStub.calledAfter(createApiStub)).toEqual(true);
        expect(deployApiStub.calledTwice).toEqual(true);
        expect(deployApiStub.calledWithExactly(
          fullGroup,
          fullApis[0]
        )).toEqual(true);
        expect(deployApiStub.calledWithExactly(
          fullGroup,
          fullApis[0]
        )).toEqual(true);

        const logs = [
          'Creating API group my-service-dev-api...',
          'Created API group my-service-dev-api',
          'Creating RAM role SLSFCInvocationFromAPIGateway...',
          'Created RAM role SLSFCInvocationFromAPIGateway',
          'Attaching RAM policy AliyunFCInvocationAccess to SLSFCInvocationFromAPIGateway...',
          'Attached RAM policy AliyunFCInvocationAccess to SLSFCInvocationFromAPIGateway',
          'Creating API sls-http-my-service-dev-currentTime...',
          'Created API sls-http-my-service-dev-currentTime',
          'Creating API sls-http-my-service-dev-currentTime2...',
          'Created API sls-http-my-service-dev-currentTime2',
          'Deploying API sls-http-my-service-dev-currentTime...',
          'Deployed API sls-http-my-service-dev-currentTime',
          'GET http://523e8dc7bbe04613b5b1d726c2a7889d-cn-hangzhou.alicloudapi.com/ping -> my-service-dev.my-service-dev-currentTime',
          'Deploying API sls-http-my-service-dev-currentTime2...',
          'Deployed API sls-http-my-service-dev-currentTime2',
          'GET http://523e8dc7bbe04613b5b1d726c2a7889d-cn-hangzhou.alicloudapi.com/ping2 -> my-service-dev.my-service-dev-currentTime2'
        ];
        expect(consoleLogStub.callCount).toEqual(logs.length);
        for (var i = 0; i < consoleLogStub.callCount; ++i) {
          expect(consoleLogStub.calledWithExactly(logs[i])).toEqual(true);
        }
      });
    });

    it('should update apis properly', () => {
      getApiGroupStub.returns(BbPromise.resolve(fullGroup));
      createApiGroupStub.returns(BbPromise.resolve());
      getApiRoleStub.returns(BbPromise.resolve(fullRole));
      createApiRoleStub.returns(BbPromise.resolve());
      getPoliciesStub.returns(BbPromise.resolve(role.Policies));
      createPolicyStub.returns(BbPromise.resolve());
      getApisStub.returns(BbPromise.resolve(fullApis));
      createApiStub.returns(BbPromise.resolve());
      updateApiStub.onCall(0).returns(BbPromise.resolve(fullApis[0]));
      updateApiStub.onCall(1).returns(BbPromise.resolve(fullApis[1]));
      deployApiStub.returns(BbPromise.resolve());

      return aliyunDeploy.setupTriggers().then(() => {
        expect(getApiGroupStub.calledOnce).toEqual(true);
        expect(getApiGroupStub.calledWithExactly('my-service-dev-api')).toEqual(true);

        expect(createApiGroupStub.called).toEqual(false);

        expect(getApiRoleStub.calledAfter(getApiGroupStub)).toEqual(true);
        expect(getApiRoleStub.calledOnce).toEqual(true);
        expect(getApiRoleStub.calledWithExactly('SLSFCInvocationFromAPIGateway')).toEqual(true);

        expect(createApiRoleStub.called).toEqual(false);

        expect(getPoliciesStub.calledAfter(getApiRoleStub)).toEqual(true);
        expect(getPoliciesStub.called).toEqual(true);
        expect(getPoliciesStub.calledWithExactly(role)).toEqual(true);

        expect(createPolicyStub.called).toEqual(false);

        expect(getApisStub.calledAfter(getPoliciesStub)).toEqual(true);
        expect(getApisStub.calledOnce).toEqual(true);
        expect(getApisStub.calledWithExactly({
          GroupId: fullGroup.GroupId
        })).toEqual(true);

        expect(createApiStub.called).toEqual(false);

        expect(updateApiStub.calledAfter(getApisStub)).toEqual(true);
        expect(updateApiStub.calledTwice).toEqual(true);
        expect(updateApiStub.calledWithExactly(
          fullGroup,
          fullRole,
          Object.assign({ApiId: fullApis[0].ApiId}, apis[0])
        )).toEqual(true);
        expect(updateApiStub.calledWithExactly(
          fullGroup,
          fullRole,
          Object.assign({ApiId: fullApis[1].ApiId}, apis[1])
        )).toEqual(true);

        expect(deployApiStub.calledAfter(updateApiStub)).toEqual(true);
        expect(deployApiStub.calledTwice).toEqual(true);
        expect(deployApiStub.calledWithExactly(
          fullGroup,
          fullApis[0]
        )).toEqual(true);
        expect(deployApiStub.calledWithExactly(
          fullGroup,
          fullApis[0]
        )).toEqual(true);

        const logs = [
          'API group my-service-dev-api exists.',
          'RAM role SLSFCInvocationFromAPIGateway exists.',
          'RAM policy AliyunFCInvocationAccess exists.',
          'Updating API sls-http-my-service-dev-currentTime...',
          'Updated API sls-http-my-service-dev-currentTime',
          'Updating API sls-http-my-service-dev-currentTime2...',
          'Updated API sls-http-my-service-dev-currentTime2',
          'Deploying API sls-http-my-service-dev-currentTime...',
          'Deployed API sls-http-my-service-dev-currentTime',
          'GET http://523e8dc7bbe04613b5b1d726c2a7889d-cn-hangzhou.alicloudapi.com/ping -> my-service-dev.my-service-dev-currentTime',
          'Deploying API sls-http-my-service-dev-currentTime2...',
          'Deployed API sls-http-my-service-dev-currentTime2',
          'GET http://523e8dc7bbe04613b5b1d726c2a7889d-cn-hangzhou.alicloudapi.com/ping2 -> my-service-dev.my-service-dev-currentTime2'
        ];
        expect(consoleLogStub.callCount).toEqual(logs.length);
        for (var i = 0; i < consoleLogStub.callCount; ++i) {
          expect(consoleLogStub.calledWithExactly(logs[i])).toEqual(true);
        }
      });
    });
  });
});
